server:
  port: 8010
spring:
  application:
    name: xiaoshop-cart
  profiles:
    active: default
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.56.11
    port: 6379
logging:
  level:
    com.xjzhang.xiaoshop.cart: debug
