server:
  port: 7002
spring:
  application:
    name: xiaoshop-gateway
  profiles:
    active: default
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: product_route
          uri: lb://xiaoshop-product
          predicates:
            - Path=/api/pro/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
      sentinel:
        transport:
          dashboard: localhost:8080
logging:
  level:
    com.xjzhang: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'
